name: Build and Deploy Slides

on:
  push:
    branches: [ main ]  
  workflow_dispatch:    # Allows manual triggering from the GitHub UI

jobs:
  # Build the slides
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Needed for pushing to gh-pages branch
      pages: write         # Needed for deployment to Pages
      id-token: write      # Needed for deployment to Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: foss-presentation:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build slides
        run: |
          mkdir -p site
          docker run --rm -v ${{ github.workspace }}/slides:/slides -v ${{ github.workspace }}/site:/slides/site foss-presentation build
          ls ${{ github.workspace }}/slides/site/
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/slides/site/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
