name: Build and Deploy Slides

on:
  push:
    branches: [ main ]  
  workflow_dispatch:    # Allows manual triggering from the GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing to gh-pages branch
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: foss-presentation:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build slides
        run: |
          mkdir -p site
          docker run --rm -v ${{ github.workspace }}/slides:/slides -v ${{ github.workspace }}/site:/slides/site foss-presentation build
      
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - id: deployment
        uses: actions/deploy-pages@v4
